repos:
  # Prevent direct commits to main
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
  # Format & lint with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  # Format & lint templates with djLint
  - repo: https://github.com/djlint/djLint
    rev: v1.46.1
    hooks:
      - id: djlint-django
      - id: djlint-reformat-django